# Site settings
title: Studio Sudal
email: jhjh.bike@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "studiosudal.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: studiosudal

# Build settings
markdown: kramdown
